
package gui;

import java.util.List;

/**
 *
 * @author dpf
 */
class SkillPanel extends javax.swing.JPanel {
    
    private final String name;

    /**
     * Creates new form SkillPanel
     * @param name
     * @param levels
     */
    public SkillPanel(String name, List<String> levels) {
        initComponents();
        this.name = name;
        labelAttribute.setText(name);
        for(String lvl: levels){
            cbLevels.addItem(lvl);
        }
    }
    
    public boolean isSelected(){
        return chbAttribute.isSelected();
    }
    
    public String getSkillName(){
        return name;
    }
    
    public String getLevelSelected(){
        String lvl = "";
        try{
            lvl = cbLevels.getSelectedItem().toString();
        }catch(NullPointerException e){
            
        }
        return lvl;
    }
    
    public boolean isCrlf(){
        return chbCrlf.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chbAttribute = new javax.swing.JCheckBox();
        labelAttribute = new javax.swing.JLabel();
        cbLevels = new javax.swing.JComboBox();
        chbCrlf = new javax.swing.JCheckBox();

        chbAttribute.setSelected(true);

        labelAttribute.setText("skill");

        cbLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLevelsActionPerformed(evt);
            }
        });

        chbCrlf.setSelected(true);
        chbCrlf.setText("crlf");
        chbCrlf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCrlfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chbAttribute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAttribute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(cbLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbCrlf))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbAttribute)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbLevels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chbCrlf)
                        .addComponent(labelAttribute)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbLevelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLevelsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLevelsActionPerformed

    private void chbCrlfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCrlfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbCrlfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbLevels;
    private javax.swing.JCheckBox chbAttribute;
    private javax.swing.JCheckBox chbCrlf;
    private javax.swing.JLabel labelAttribute;
    // End of variables declaration//GEN-END:variables
}
